"""Domain models shared across the framework.

These Pydantic models are the single source of truth for the shape of data as it
flows through the pipeline: attack -> execution -> judgement -> report. They are
also (de)serialized to/from the database and the JSON regression baseline.
"""

from __future__ import annotations

import enum
from datetime import datetime, timezone
from typing import Optional
from uuid import uuid4

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    """Timezone-aware UTC timestamp (naive datetimes cause subtle bugs)."""
    return datetime.now(timezone.utc)


def _new_id() -> str:
    """Short, URL-safe unique identifier."""
    return uuid4().hex


class RiskScore(str, enum.Enum):
    """Judge verdict for a single response, ordered from safest to most severe.

    The string values are stored in the DB and rendered in reports. The numeric
    ordering (see :data:`SCORE_ORDER`) is used for thresholds and aggregation.
    """

    PASS = "pass"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# Numeric severity used for comparisons/thresholds. Higher == more severe.
SCORE_ORDER: dict[RiskScore, int] = {
    RiskScore.PASS: 0,
    RiskScore.LOW: 1,
    RiskScore.MEDIUM: 2,
    RiskScore.HIGH: 3,
    RiskScore.CRITICAL: 4,
}

# A breach is any outcome more severe than a clean pass.
BREACH_SCORES: frozenset[RiskScore] = frozenset(
    {RiskScore.LOW, RiskScore.MEDIUM, RiskScore.HIGH, RiskScore.CRITICAL}
)


class AttackPrompt(BaseModel):
    """A single adversarial prompt generated by the attacker (or mutator)."""

    id: str = Field(default_factory=_new_id)
    category: str                          # e.g. "jailbreak" (see categories.py)
    variant: int                           # 1-based index within its category
    prompt: str                            # the adversarial user message
    rationale: str = ""                    # attacker's CoT: why this might work
    # Mutation lineage. None for freshly generated prompts; set to the parent's
    # id when produced by the mutation engine.
    parent_id: Optional[str] = None
    mutation_round: int = 0                # 0 = original, 1+ = mutated
    mutation_technique: Optional[str] = None  # e.g. "base64", "paraphrase"
    created_at: datetime = Field(default_factory=_utcnow)


class TargetResponse(BaseModel):
    """The raw response captured from the target LLM for one attack prompt."""

    id: str = Field(default_factory=_new_id)
    attack_id: str
    content: str
    # Wall-clock latency of the target call, useful for the dashboard.
    latency_ms: int = 0
    error: Optional[str] = None            # set if the target call failed
    created_at: datetime = Field(default_factory=_utcnow)


class Judgement(BaseModel):
    """The judge agent's structured verdict for a single response."""

    id: str = Field(default_factory=_new_id)
    attack_id: str
    response_id: str
    score: RiskScore
    breach_type: str                       # short label, e.g. "system_prompt_leak"
    complied: bool                         # did the target do what the attack wanted?
    leaked_info: bool                      # did it leak system prompt / secrets?
    refused_cleanly: bool
    reasoning: str                         # judge's justification
    created_at: datetime = Field(default_factory=_utcnow)


class AttackResult(BaseModel):
    """One fully-evaluated attack: prompt + response + judgement.

    This is the atomic unit the engine emits and the reporter aggregates.
    """

    attack: AttackPrompt
    response: TargetResponse
    judgement: Judgement

    @property
    def is_breach(self) -> bool:
        return self.judgement.score in BREACH_SCORES


class Campaign(BaseModel):
    """Metadata for a single red-team run."""

    id: str = Field(default_factory=_new_id)
    target_name: str
    target_model: str
    provider: str                          # "anthropic" or "mock"
    categories: list[str]
    variants_per_category: int
    started_at: datetime = Field(default_factory=_utcnow)
    finished_at: Optional[datetime] = None
    total_attacks: int = 0
    total_breaches: int = 0
